### ISSUE TITLE
Kodi Error received when connecting to ExpressVPN for the first time

### ISSUE THREAD

**Issue by MatrixMagician** [Zomboided/service.vpn.manager#243]
Hi Zomboided,
I have recently acquired a Rasberry Pi 3 B and installed LibreELEC 9.0.2 and
 Kodi (18.2 Git:newclock5_18.2-Leia).
I then installed your addon and used the Wizard to use the ExpressVPN and while I can apparently connect, shortly after connection validation I receive an on-screen error "Addon Error,please check the logs".  I checked the Kodi log and I see the following Python error:

```
2019-06-30 19:27:29.654 T:1815065456   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.UnicodeEncodeError'>
                                            **Error Contents: 'ascii' codec can't encode character u'\xce' in position 117: ordinal not in range(128)**
                                            Traceback (most recent call last):
                                              File "/storage/.kodi/addons/service.vpn.manager/connect.py", line 51, in `<module>`
                                                connectVPN(str(connection_order), "")
                                              File "/storage/.kodi/addons/service.vpn.manager/libs/common.py", line 2017, in connectVPN
                                                infoTrace("common.py", dialog_message)
                                              File "/storage/.kodi/addons/service.vpn.manager/libs/utility.py", line 63, in infoTrace
                                                `xbmc.log(msg=log,` level=xbmc.LOGNOTICE)
                                            UnicodeEncodeError: 'ascii' codec can't encode character u'\xce' in position 117: ordinal not in range(128)
                                            -->End of Python script error report<--
```
From my understanding is that a [non-ascii character](https://www.charbase.com/00ce-unicode-latin-capital-letter-i-with-circumflex) is being passed which it cannot interpret.  I don't know where that character comes from as it is not in the username or password.
 Let me know if you want the full Kodi log.  Thanks.

**Comment by Zomboided** [comment]
Need log with debug set on in the vpn mgr advanced settings menu

**Comment by Zomboided** [comment]
Actually don't need a log, I found this and will fix in the next release
