### ISSUE TITLE
unable to download PIA files

### ISSUE THREAD

**Issue by njayarama** [Zomboided/service.vpn.manager#62]
Hi, with latest version getting below error on RPi2, please help to fix the issue.

16:46:35.143 T:1769993120  NOTICE: VPN Mgr : (vpnproviders.py) Checking downloaded ovpn files for PIA with GitHub files
16:46:35.267 T:1769993120   ERROR: VPN Mgr : (vpnproviders.py) Can't get the metadata from Github for PIA
16:46:35.267 T:1769993120   ERROR: VPN Mgr : (vpnproviders.py) <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:661)>

log available @ https://pastebin.com/k16cxs3r

Thanks for your contribution!

**Comment by Zomboided** [comment]
Have you used VPN Mgr v4.x on Kodi 17 previously? Or is this a 4.0.2 problem where it worked with 4.0.0 or 4.0.1?

**Comment by Zomboided** [comment]
Also, this is in the error log earlier on, with the same issue.  Do you have some kinda SSL certificate issue with the build you're using?  I installed vanilla LE8 on my RPi2 yesterday and I just did a reset of everything and it fetched the PIA files, no problem.
 :

16:33:18.869 T:1567617952   ERROR: ## LibreELEC Addon ## oe::load_url(https://update.libreelec.tv/updates.php?i=ff93f4d9d4155272d070a34c53a0c1b1&d=LibreELEC&pa=RPi2.arm&v=8.0.1&l=0
                                            ) ## ERROR: (URLError(SSLError(1, u'[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:661)'),))
16:33:18.871 T:1567617952   ERROR: Traceback (most recent call last):
                                              File "/home/chewitt/LibreELEC.80-official/build.LibreELEC-RPi2.arm-8.0.1/LibreELEC-settings-6336f1e/.install_pkg/usr/share/kodi/addons/service.libreelec.settings/oe.py", line 271, in load_url
                                              File "/usr/lib/python2.7/urllib2.py", line 154, in urlopen
                                              File "/usr/lib/python2.7/urllib2.py", line 429, in open
                                              File "/usr/lib/python2.7/urllib2.py", line 447, in _open
                                              File "/usr/lib/python2.7/urllib2.py", line 407, in _call_chain
                                              File "/usr/lib/python2.7/urllib2.py", line 1241, in https_open
                                              File "/usr/lib/python2.7/urllib2.py", line 1198, in do_open
                                            URLError: <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:661)>
16:33:18.877 T:1567617952   ERROR: ## LibreELEC Addon ## system::check_updates_v2 ## ERROR: (TypeError('expected string or buffer',))
16:33:18.878 T:1567617952   ERROR: Traceback (most recent call last):
                                              File "/home/chewitt/LibreELEC.80-official/build.LibreELEC-RPi2.arm-8.0.1/LibreELEC-settings-6336f1e/.install_pkg/usr/share/kodi/addons/service.libreelec.settings/resources/lib/modules/system.py", line 768, in check_updates_v2
                                              File "/usr/lib/python2.7/json/__init__.py", line 339, in loads
                                              File "/usr/lib/python2.7/json/decoder.py", line 364, in decode
                                            TypeError: expected string or buffer

**Comment by Zomboided** [comment]
Here's the URL it's using if you want to test that via a browser
https://raw.githubusercontent.com/Zomboided/service.vpn.manager.providers/master/PIA/METADATA.txt

**Comment by njayarama** [comment]
thanks for quick replies.

initially with stock vpn manager v 4.0.3 did not work, then uninstalled and downloaded v 4.0.2 from here.
here log attached.
[kodi_17-02-26_16-44-41.txt](https://github.com/Zomboided/service.vpn.manager/files/918531/kodi_17-02-26_16-44-41.txt)

please help me how to fix SSL: CERTIFICATE_VERIFY_FAILED issue.

**Comment by Zomboided** [comment]
I don't think this is a problem with my add-on.  I've posted a thread here : https://forum.libreelec.tv/thread-7454.html to see if anyone can shed any light on why this is happening to you and not to me on identical hardware/set ups.  I'll reopen this if it is a problem with my add-on and not your environment.

**Comment by njayarama** [comment]
finally it worked on RPi2, re-flashed LE8 on my Noobs SD card. Not sure what went wrong on first attempt.
Thanks Zomboided for your add-on, VPN Manger working very well...
